// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rider.proto
// Protobuf C++ Version: 6.33.1

#include "rider.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace vahan_mesh {

inline constexpr RideRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        rider_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pickup_lat_{0},
        pickup_long_{0},
        dest_lat_{0},
        dest_long_{0},
        rider_rating_{0},
        requested_type_{static_cast< ::vahan_mesh::RideRequest_ServiceType >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR RideRequest::RideRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RideRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RideRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RideRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RideRequestDefaultTypeInternal() {}
  union {
    RideRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RideRequestDefaultTypeInternal _RideRequest_default_instance_;

inline constexpr Cab::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        cab_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        lat_{0},
        lon_{0},
        is_available_{false} {}

template <typename>
PROTOBUF_CONSTEXPR Cab::Cab(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Cab_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CabDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CabDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CabDefaultTypeInternal() {}
  union {
    Cab _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CabDefaultTypeInternal _Cab_default_instance_;
}  // namespace vahan_mesh
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_rider_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_rider_2eproto = nullptr;
const ::uint32_t
    TableStruct_rider_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::vahan_mesh::RideRequest, _impl_._has_bits_),
        10, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::vahan_mesh::RideRequest, _impl_.rider_id_),
        PROTOBUF_FIELD_OFFSET(::vahan_mesh::RideRequest, _impl_.pickup_lat_),
        PROTOBUF_FIELD_OFFSET(::vahan_mesh::RideRequest, _impl_.pickup_long_),
        PROTOBUF_FIELD_OFFSET(::vahan_mesh::RideRequest, _impl_.dest_lat_),
        PROTOBUF_FIELD_OFFSET(::vahan_mesh::RideRequest, _impl_.dest_long_),
        PROTOBUF_FIELD_OFFSET(::vahan_mesh::RideRequest, _impl_.rider_rating_),
        PROTOBUF_FIELD_OFFSET(::vahan_mesh::RideRequest, _impl_.requested_type_),
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::vahan_mesh::Cab, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::vahan_mesh::Cab, _impl_.cab_id_),
        PROTOBUF_FIELD_OFFSET(::vahan_mesh::Cab, _impl_.lat_),
        PROTOBUF_FIELD_OFFSET(::vahan_mesh::Cab, _impl_.lon_),
        PROTOBUF_FIELD_OFFSET(::vahan_mesh::Cab, _impl_.is_available_),
        0,
        1,
        2,
        3,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::vahan_mesh::RideRequest)},
        {17, sizeof(::vahan_mesh::Cab)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::vahan_mesh::_RideRequest_default_instance_._instance,
    &::vahan_mesh::_Cab_default_instance_._instance,
};
const char descriptor_table_protodef_rider_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013rider.proto\022\nvahan_mesh\"\361\001\n\013RideReques"
    "t\022\020\n\010rider_id\030\001 \001(\t\022\022\n\npickup_lat\030\002 \001(\001\022"
    "\023\n\013pickup_long\030\003 \001(\001\022\020\n\010dest_lat\030\004 \001(\001\022\021"
    "\n\tdest_long\030\005 \001(\001\022\024\n\014rider_rating\030\006 \001(\005\022"
    ";\n\016requested_type\030\007 \001(\0162#.vahan_mesh.Rid"
    "eRequest.ServiceType\"/\n\013ServiceType\022\013\n\007E"
    "CONOMY\020\000\022\013\n\007PREMIUM\020\001\022\006\n\002EV\020\002\"E\n\003Cab\022\016\n\006"
    "cab_id\030\001 \001(\t\022\013\n\003lat\030\002 \001(\001\022\013\n\003lon\030\003 \001(\001\022\024"
    "\n\014is_available\030\004 \001(\010b\006proto3"
};
static ::absl::once_flag descriptor_table_rider_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_rider_2eproto = {
    false,
    false,
    348,
    descriptor_table_protodef_rider_2eproto,
    "rider.proto",
    &descriptor_table_rider_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_rider_2eproto::offsets,
    file_level_enum_descriptors_rider_2eproto,
    file_level_service_descriptors_rider_2eproto,
};
namespace vahan_mesh {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL RideRequest_ServiceType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_rider_2eproto);
  return file_level_enum_descriptors_rider_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t RideRequest_ServiceType_internal_data_[] = {
    196608u, 0u, };
// ===================================================================

class RideRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RideRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RideRequest, _impl_._has_bits_);
};

RideRequest::RideRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RideRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:vahan_mesh.RideRequest)
}
PROTOBUF_NDEBUG_INLINE RideRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::vahan_mesh::RideRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        rider_id_(arena, from.rider_id_) {}

RideRequest::RideRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RideRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RideRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RideRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, pickup_lat_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, pickup_lat_),
           offsetof(Impl_, requested_type_) -
               offsetof(Impl_, pickup_lat_) +
               sizeof(Impl_::requested_type_));

  // @@protoc_insertion_point(copy_constructor:vahan_mesh.RideRequest)
}
PROTOBUF_NDEBUG_INLINE RideRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        rider_id_(arena) {}

inline void RideRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, pickup_lat_),
           0,
           offsetof(Impl_, requested_type_) -
               offsetof(Impl_, pickup_lat_) +
               sizeof(Impl_::requested_type_));
}
RideRequest::~RideRequest() {
  // @@protoc_insertion_point(destructor:vahan_mesh.RideRequest)
  SharedDtor(*this);
}
inline void RideRequest::SharedDtor(MessageLite& self) {
  RideRequest& this_ = static_cast<RideRequest&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.rider_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RideRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RideRequest(arena);
}
constexpr auto RideRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RideRequest),
                                            alignof(RideRequest));
}
constexpr auto RideRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RideRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RideRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RideRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RideRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RideRequest>(), &RideRequest::ByteSizeLong,
              &RideRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RideRequest, _impl_._cached_size_),
          false,
      },
      &RideRequest::kDescriptorMethods,
      &descriptor_table_rider_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RideRequest_class_data_ =
        RideRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RideRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RideRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RideRequest_class_data_.tc_table);
  return RideRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 0, 39, 2>
RideRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RideRequest, _impl_._has_bits_),
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RideRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::vahan_mesh::RideRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string rider_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(RideRequest, _impl_.rider_id_)}},
    // double pickup_lat = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 1, 0,
      PROTOBUF_FIELD_OFFSET(RideRequest, _impl_.pickup_lat_)}},
    // double pickup_long = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 2, 0,
      PROTOBUF_FIELD_OFFSET(RideRequest, _impl_.pickup_long_)}},
    // double dest_lat = 4;
    {::_pbi::TcParser::FastF64S1,
     {33, 3, 0,
      PROTOBUF_FIELD_OFFSET(RideRequest, _impl_.dest_lat_)}},
    // double dest_long = 5;
    {::_pbi::TcParser::FastF64S1,
     {41, 4, 0,
      PROTOBUF_FIELD_OFFSET(RideRequest, _impl_.dest_long_)}},
    // int32 rider_rating = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RideRequest, _impl_.rider_rating_), 5>(),
     {48, 5, 0,
      PROTOBUF_FIELD_OFFSET(RideRequest, _impl_.rider_rating_)}},
    // .vahan_mesh.RideRequest.ServiceType requested_type = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RideRequest, _impl_.requested_type_), 6>(),
     {56, 6, 0,
      PROTOBUF_FIELD_OFFSET(RideRequest, _impl_.requested_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string rider_id = 1;
    {PROTOBUF_FIELD_OFFSET(RideRequest, _impl_.rider_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // double pickup_lat = 2;
    {PROTOBUF_FIELD_OFFSET(RideRequest, _impl_.pickup_lat_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double pickup_long = 3;
    {PROTOBUF_FIELD_OFFSET(RideRequest, _impl_.pickup_long_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double dest_lat = 4;
    {PROTOBUF_FIELD_OFFSET(RideRequest, _impl_.dest_lat_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double dest_long = 5;
    {PROTOBUF_FIELD_OFFSET(RideRequest, _impl_.dest_long_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // int32 rider_rating = 6;
    {PROTOBUF_FIELD_OFFSET(RideRequest, _impl_.rider_rating_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // .vahan_mesh.RideRequest.ServiceType requested_type = 7;
    {PROTOBUF_FIELD_OFFSET(RideRequest, _impl_.requested_type_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
    "\26\10\0\0\0\0\0\0"
    "vahan_mesh.RideRequest"
    "rider_id"
  }},
};
PROTOBUF_NOINLINE void RideRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:vahan_mesh.RideRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.rider_id_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000007eU)) {
    ::memset(&_impl_.pickup_lat_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.requested_type_) -
        reinterpret_cast<char*>(&_impl_.pickup_lat_)) + sizeof(_impl_.requested_type_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RideRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RideRequest& this_ = static_cast<const RideRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RideRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RideRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:vahan_mesh.RideRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string rider_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_rider_id().empty()) {
      const ::std::string& _s = this_._internal_rider_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "vahan_mesh.RideRequest.rider_id");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // double pickup_lat = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_pickup_lat()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          2, this_._internal_pickup_lat(), target);
    }
  }

  // double pickup_long = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_pickup_long()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          3, this_._internal_pickup_long(), target);
    }
  }

  // double dest_lat = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_dest_lat()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          4, this_._internal_dest_lat(), target);
    }
  }

  // double dest_long = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_dest_long()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          5, this_._internal_dest_long(), target);
    }
  }

  // int32 rider_rating = 6;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_rider_rating() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<6>(
              stream, this_._internal_rider_rating(), target);
    }
  }

  // .vahan_mesh.RideRequest.ServiceType requested_type = 7;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_requested_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          7, this_._internal_requested_type(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vahan_mesh.RideRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RideRequest::ByteSizeLong(const MessageLite& base) {
  const RideRequest& this_ = static_cast<const RideRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RideRequest::ByteSizeLong() const {
  const RideRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:vahan_mesh.RideRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    // string rider_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_rider_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_rider_id());
      }
    }
    // double pickup_lat = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_pickup_lat()) != 0) {
        total_size += 9;
      }
    }
    // double pickup_long = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_pickup_long()) != 0) {
        total_size += 9;
      }
    }
    // double dest_lat = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_dest_lat()) != 0) {
        total_size += 9;
      }
    }
    // double dest_long = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_dest_long()) != 0) {
        total_size += 9;
      }
    }
    // int32 rider_rating = 6;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_rider_rating() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_rider_rating());
      }
    }
    // .vahan_mesh.RideRequest.ServiceType requested_type = 7;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_requested_type() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_requested_type());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RideRequest::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<RideRequest*>(&to_msg);
  auto& from = static_cast<const RideRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:vahan_mesh.RideRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_rider_id().empty()) {
        _this->_internal_set_rider_id(from._internal_rider_id());
      } else {
        if (_this->_impl_.rider_id_.IsDefault()) {
          _this->_internal_set_rider_id("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_pickup_lat()) != 0) {
        _this->_impl_.pickup_lat_ = from._impl_.pickup_lat_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_pickup_long()) != 0) {
        _this->_impl_.pickup_long_ = from._impl_.pickup_long_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_dest_lat()) != 0) {
        _this->_impl_.dest_lat_ = from._impl_.dest_lat_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_dest_long()) != 0) {
        _this->_impl_.dest_long_ = from._impl_.dest_long_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_rider_rating() != 0) {
        _this->_impl_.rider_rating_ = from._impl_.rider_rating_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_requested_type() != 0) {
        _this->_impl_.requested_type_ = from._impl_.requested_type_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RideRequest::CopyFrom(const RideRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:vahan_mesh.RideRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RideRequest::InternalSwap(RideRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.rider_id_, &other->_impl_.rider_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RideRequest, _impl_.requested_type_)
      + sizeof(RideRequest::_impl_.requested_type_)
      - PROTOBUF_FIELD_OFFSET(RideRequest, _impl_.pickup_lat_)>(
          reinterpret_cast<char*>(&_impl_.pickup_lat_),
          reinterpret_cast<char*>(&other->_impl_.pickup_lat_));
}

::google::protobuf::Metadata RideRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Cab::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Cab>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Cab, _impl_._has_bits_);
};

Cab::Cab(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Cab_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:vahan_mesh.Cab)
}
PROTOBUF_NDEBUG_INLINE Cab::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::vahan_mesh::Cab& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        cab_id_(arena, from.cab_id_) {}

Cab::Cab(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Cab& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Cab_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Cab* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, lat_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, lat_),
           offsetof(Impl_, is_available_) -
               offsetof(Impl_, lat_) +
               sizeof(Impl_::is_available_));

  // @@protoc_insertion_point(copy_constructor:vahan_mesh.Cab)
}
PROTOBUF_NDEBUG_INLINE Cab::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        cab_id_(arena) {}

inline void Cab::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, lat_),
           0,
           offsetof(Impl_, is_available_) -
               offsetof(Impl_, lat_) +
               sizeof(Impl_::is_available_));
}
Cab::~Cab() {
  // @@protoc_insertion_point(destructor:vahan_mesh.Cab)
  SharedDtor(*this);
}
inline void Cab::SharedDtor(MessageLite& self) {
  Cab& this_ = static_cast<Cab&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.cab_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Cab::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Cab(arena);
}
constexpr auto Cab::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Cab),
                                            alignof(Cab));
}
constexpr auto Cab::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Cab_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Cab::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Cab>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Cab::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Cab>(), &Cab::ByteSizeLong,
              &Cab::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Cab, _impl_._cached_size_),
          false,
      },
      &Cab::kDescriptorMethods,
      &descriptor_table_rider_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Cab_class_data_ =
        Cab::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Cab::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Cab_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Cab_class_data_.tc_table);
  return Cab_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 29, 2>
Cab::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Cab, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Cab_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::vahan_mesh::Cab>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool is_available = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Cab, _impl_.is_available_), 3>(),
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(Cab, _impl_.is_available_)}},
    // string cab_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(Cab, _impl_.cab_id_)}},
    // double lat = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 1, 0,
      PROTOBUF_FIELD_OFFSET(Cab, _impl_.lat_)}},
    // double lon = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 2, 0,
      PROTOBUF_FIELD_OFFSET(Cab, _impl_.lon_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string cab_id = 1;
    {PROTOBUF_FIELD_OFFSET(Cab, _impl_.cab_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // double lat = 2;
    {PROTOBUF_FIELD_OFFSET(Cab, _impl_.lat_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double lon = 3;
    {PROTOBUF_FIELD_OFFSET(Cab, _impl_.lon_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // bool is_available = 4;
    {PROTOBUF_FIELD_OFFSET(Cab, _impl_.is_available_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\16\6\0\0\0\0\0\0"
    "vahan_mesh.Cab"
    "cab_id"
  }},
};
PROTOBUF_NOINLINE void Cab::Clear() {
// @@protoc_insertion_point(message_clear_start:vahan_mesh.Cab)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.cab_id_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000000eU)) {
    ::memset(&_impl_.lat_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.is_available_) -
        reinterpret_cast<char*>(&_impl_.lat_)) + sizeof(_impl_.is_available_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Cab::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Cab& this_ = static_cast<const Cab&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Cab::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Cab& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:vahan_mesh.Cab)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string cab_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_cab_id().empty()) {
      const ::std::string& _s = this_._internal_cab_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "vahan_mesh.Cab.cab_id");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // double lat = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_lat()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          2, this_._internal_lat(), target);
    }
  }

  // double lon = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_lon()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          3, this_._internal_lon(), target);
    }
  }

  // bool is_available = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_is_available() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          4, this_._internal_is_available(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vahan_mesh.Cab)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Cab::ByteSizeLong(const MessageLite& base) {
  const Cab& this_ = static_cast<const Cab&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Cab::ByteSizeLong() const {
  const Cab& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:vahan_mesh.Cab)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // string cab_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_cab_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_cab_id());
      }
    }
    // double lat = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_lat()) != 0) {
        total_size += 9;
      }
    }
    // double lon = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_lon()) != 0) {
        total_size += 9;
      }
    }
    // bool is_available = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_is_available() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Cab::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Cab*>(&to_msg);
  auto& from = static_cast<const Cab&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:vahan_mesh.Cab)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_cab_id().empty()) {
        _this->_internal_set_cab_id(from._internal_cab_id());
      } else {
        if (_this->_impl_.cab_id_.IsDefault()) {
          _this->_internal_set_cab_id("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_lat()) != 0) {
        _this->_impl_.lat_ = from._impl_.lat_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_lon()) != 0) {
        _this->_impl_.lon_ = from._impl_.lon_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_is_available() != 0) {
        _this->_impl_.is_available_ = from._impl_.is_available_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Cab::CopyFrom(const Cab& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:vahan_mesh.Cab)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Cab::InternalSwap(Cab* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.cab_id_, &other->_impl_.cab_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Cab, _impl_.is_available_)
      + sizeof(Cab::_impl_.is_available_)
      - PROTOBUF_FIELD_OFFSET(Cab, _impl_.lat_)>(
          reinterpret_cast<char*>(&_impl_.lat_),
          reinterpret_cast<char*>(&other->_impl_.lat_));
}

::google::protobuf::Metadata Cab::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace vahan_mesh
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_rider_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
