// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rider.proto
// Protobuf C++ Version: 6.33.1

#ifndef rider_2eproto_2epb_2eh
#define rider_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_rider_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_rider_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_rider_2eproto;
}  // extern "C"
namespace vahan_mesh {
enum RideRequest_ServiceType : int;
extern const uint32_t RideRequest_ServiceType_internal_data_[];
class Cab;
struct CabDefaultTypeInternal;
extern CabDefaultTypeInternal _Cab_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Cab_class_data_;
class RideRequest;
struct RideRequestDefaultTypeInternal;
extern RideRequestDefaultTypeInternal _RideRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RideRequest_class_data_;
}  // namespace vahan_mesh
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::vahan_mesh::RideRequest_ServiceType_internal_data_>
    internal::EnumTraitsImpl::value<::vahan_mesh::RideRequest_ServiceType>;
}  // namespace protobuf
}  // namespace google

namespace vahan_mesh {
enum RideRequest_ServiceType : int {
  RideRequest_ServiceType_ECONOMY = 0,
  RideRequest_ServiceType_PREMIUM = 1,
  RideRequest_ServiceType_EV = 2,
  RideRequest_ServiceType_RideRequest_ServiceType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  RideRequest_ServiceType_RideRequest_ServiceType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t RideRequest_ServiceType_internal_data_[];
inline constexpr RideRequest_ServiceType RideRequest_ServiceType_ServiceType_MIN =
    static_cast<RideRequest_ServiceType>(0);
inline constexpr RideRequest_ServiceType RideRequest_ServiceType_ServiceType_MAX =
    static_cast<RideRequest_ServiceType>(2);
inline bool RideRequest_ServiceType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int RideRequest_ServiceType_ServiceType_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL RideRequest_ServiceType_descriptor();
template <typename T>
const ::std::string& RideRequest_ServiceType_Name(T value) {
  static_assert(::std::is_same<T, RideRequest_ServiceType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to ServiceType_Name().");
  return RideRequest_ServiceType_Name(static_cast<RideRequest_ServiceType>(value));
}
template <>
inline const ::std::string& RideRequest_ServiceType_Name(RideRequest_ServiceType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<RideRequest_ServiceType_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool RideRequest_ServiceType_Parse(
    ::absl::string_view name, RideRequest_ServiceType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<RideRequest_ServiceType>(RideRequest_ServiceType_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class RideRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:vahan_mesh.RideRequest) */ {
 public:
  inline RideRequest() : RideRequest(nullptr) {}
  ~RideRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RideRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RideRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RideRequest(::google::protobuf::internal::ConstantInitialized);

  inline RideRequest(const RideRequest& from) : RideRequest(nullptr, from) {}
  inline RideRequest(RideRequest&& from) noexcept
      : RideRequest(nullptr, ::std::move(from)) {}
  inline RideRequest& operator=(const RideRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline RideRequest& operator=(RideRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RideRequest& default_instance() {
    return *reinterpret_cast<const RideRequest*>(
        &_RideRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RideRequest& a, RideRequest& b) { a.Swap(&b); }
  inline void Swap(RideRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RideRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RideRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RideRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RideRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RideRequest& from) { RideRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RideRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "vahan_mesh.RideRequest"; }

  explicit RideRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RideRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RideRequest& from);
  RideRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RideRequest&& from) noexcept
      : RideRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using ServiceType = RideRequest_ServiceType;
  static constexpr ServiceType ECONOMY = RideRequest_ServiceType_ECONOMY;
  static constexpr ServiceType PREMIUM = RideRequest_ServiceType_PREMIUM;
  static constexpr ServiceType EV = RideRequest_ServiceType_EV;
  static inline bool ServiceType_IsValid(int value) {
    return RideRequest_ServiceType_IsValid(value);
  }
  static constexpr ServiceType ServiceType_MIN = RideRequest_ServiceType_ServiceType_MIN;
  static constexpr ServiceType ServiceType_MAX = RideRequest_ServiceType_ServiceType_MAX;
  static constexpr int ServiceType_ARRAYSIZE = RideRequest_ServiceType_ServiceType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ServiceType_descriptor() {
    return RideRequest_ServiceType_descriptor();
  }
  template <typename T>
  static inline const ::std::string& ServiceType_Name(T value) {
    return RideRequest_ServiceType_Name(value);
  }
  static inline bool ServiceType_Parse(
      ::absl::string_view name, ServiceType* PROTOBUF_NONNULL value) {
    return RideRequest_ServiceType_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kRiderIdFieldNumber = 1,
    kPickupLatFieldNumber = 2,
    kPickupLongFieldNumber = 3,
    kDestLatFieldNumber = 4,
    kDestLongFieldNumber = 5,
    kRiderRatingFieldNumber = 6,
    kRequestedTypeFieldNumber = 7,
  };
  // string rider_id = 1;
  void clear_rider_id() ;
  const ::std::string& rider_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_rider_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_rider_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_rider_id();
  void set_allocated_rider_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_rider_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_rider_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_rider_id();

  public:
  // double pickup_lat = 2;
  void clear_pickup_lat() ;
  double pickup_lat() const;
  void set_pickup_lat(double value);

  private:
  double _internal_pickup_lat() const;
  void _internal_set_pickup_lat(double value);

  public:
  // double pickup_long = 3;
  void clear_pickup_long() ;
  double pickup_long() const;
  void set_pickup_long(double value);

  private:
  double _internal_pickup_long() const;
  void _internal_set_pickup_long(double value);

  public:
  // double dest_lat = 4;
  void clear_dest_lat() ;
  double dest_lat() const;
  void set_dest_lat(double value);

  private:
  double _internal_dest_lat() const;
  void _internal_set_dest_lat(double value);

  public:
  // double dest_long = 5;
  void clear_dest_long() ;
  double dest_long() const;
  void set_dest_long(double value);

  private:
  double _internal_dest_long() const;
  void _internal_set_dest_long(double value);

  public:
  // int32 rider_rating = 6;
  void clear_rider_rating() ;
  ::int32_t rider_rating() const;
  void set_rider_rating(::int32_t value);

  private:
  ::int32_t _internal_rider_rating() const;
  void _internal_set_rider_rating(::int32_t value);

  public:
  // .vahan_mesh.RideRequest.ServiceType requested_type = 7;
  void clear_requested_type() ;
  ::vahan_mesh::RideRequest_ServiceType requested_type() const;
  void set_requested_type(::vahan_mesh::RideRequest_ServiceType value);

  private:
  ::vahan_mesh::RideRequest_ServiceType _internal_requested_type() const;
  void _internal_set_requested_type(::vahan_mesh::RideRequest_ServiceType value);

  public:
  // @@protoc_insertion_point(class_scope:vahan_mesh.RideRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 7,
                                   0, 39,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RideRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr rider_id_;
    double pickup_lat_;
    double pickup_long_;
    double dest_lat_;
    double dest_long_;
    ::int32_t rider_rating_;
    int requested_type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rider_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RideRequest_class_data_;
// -------------------------------------------------------------------

class Cab final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:vahan_mesh.Cab) */ {
 public:
  inline Cab() : Cab(nullptr) {}
  ~Cab() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Cab* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Cab));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Cab(::google::protobuf::internal::ConstantInitialized);

  inline Cab(const Cab& from) : Cab(nullptr, from) {}
  inline Cab(Cab&& from) noexcept
      : Cab(nullptr, ::std::move(from)) {}
  inline Cab& operator=(const Cab& from) {
    CopyFrom(from);
    return *this;
  }
  inline Cab& operator=(Cab&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Cab& default_instance() {
    return *reinterpret_cast<const Cab*>(
        &_Cab_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Cab& a, Cab& b) { a.Swap(&b); }
  inline void Swap(Cab* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Cab* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Cab* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Cab>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Cab& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Cab& from) { Cab::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Cab* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "vahan_mesh.Cab"; }

  explicit Cab(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Cab(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Cab& from);
  Cab(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Cab&& from) noexcept
      : Cab(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCabIdFieldNumber = 1,
    kLatFieldNumber = 2,
    kLonFieldNumber = 3,
    kIsAvailableFieldNumber = 4,
  };
  // string cab_id = 1;
  void clear_cab_id() ;
  const ::std::string& cab_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_cab_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_cab_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_cab_id();
  void set_allocated_cab_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_cab_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_cab_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_cab_id();

  public:
  // double lat = 2;
  void clear_lat() ;
  double lat() const;
  void set_lat(double value);

  private:
  double _internal_lat() const;
  void _internal_set_lat(double value);

  public:
  // double lon = 3;
  void clear_lon() ;
  double lon() const;
  void set_lon(double value);

  private:
  double _internal_lon() const;
  void _internal_set_lon(double value);

  public:
  // bool is_available = 4;
  void clear_is_available() ;
  bool is_available() const;
  void set_is_available(bool value);

  private:
  bool _internal_is_available() const;
  void _internal_set_is_available(bool value);

  public:
  // @@protoc_insertion_point(class_scope:vahan_mesh.Cab)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 29,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Cab& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr cab_id_;
    double lat_;
    double lon_;
    bool is_available_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rider_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Cab_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RideRequest

// string rider_id = 1;
inline void RideRequest::clear_rider_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rider_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& RideRequest::rider_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:vahan_mesh.RideRequest.rider_id)
  return _internal_rider_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RideRequest::set_rider_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.rider_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:vahan_mesh.RideRequest.rider_id)
}
inline ::std::string* PROTOBUF_NONNULL RideRequest::mutable_rider_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_rider_id();
  // @@protoc_insertion_point(field_mutable:vahan_mesh.RideRequest.rider_id)
  return _s;
}
inline const ::std::string& RideRequest::_internal_rider_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rider_id_.Get();
}
inline void RideRequest::_internal_set_rider_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rider_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RideRequest::_internal_mutable_rider_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.rider_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RideRequest::release_rider_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:vahan_mesh.RideRequest.rider_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.rider_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.rider_id_.Set("", GetArena());
  }
  return released;
}
inline void RideRequest::set_allocated_rider_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.rider_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.rider_id_.IsDefault()) {
    _impl_.rider_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:vahan_mesh.RideRequest.rider_id)
}

// double pickup_lat = 2;
inline void RideRequest::clear_pickup_lat() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pickup_lat_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline double RideRequest::pickup_lat() const {
  // @@protoc_insertion_point(field_get:vahan_mesh.RideRequest.pickup_lat)
  return _internal_pickup_lat();
}
inline void RideRequest::set_pickup_lat(double value) {
  _internal_set_pickup_lat(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:vahan_mesh.RideRequest.pickup_lat)
}
inline double RideRequest::_internal_pickup_lat() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pickup_lat_;
}
inline void RideRequest::_internal_set_pickup_lat(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pickup_lat_ = value;
}

// double pickup_long = 3;
inline void RideRequest::clear_pickup_long() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pickup_long_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline double RideRequest::pickup_long() const {
  // @@protoc_insertion_point(field_get:vahan_mesh.RideRequest.pickup_long)
  return _internal_pickup_long();
}
inline void RideRequest::set_pickup_long(double value) {
  _internal_set_pickup_long(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:vahan_mesh.RideRequest.pickup_long)
}
inline double RideRequest::_internal_pickup_long() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pickup_long_;
}
inline void RideRequest::_internal_set_pickup_long(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pickup_long_ = value;
}

// double dest_lat = 4;
inline void RideRequest::clear_dest_lat() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dest_lat_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline double RideRequest::dest_lat() const {
  // @@protoc_insertion_point(field_get:vahan_mesh.RideRequest.dest_lat)
  return _internal_dest_lat();
}
inline void RideRequest::set_dest_lat(double value) {
  _internal_set_dest_lat(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:vahan_mesh.RideRequest.dest_lat)
}
inline double RideRequest::_internal_dest_lat() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dest_lat_;
}
inline void RideRequest::_internal_set_dest_lat(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dest_lat_ = value;
}

// double dest_long = 5;
inline void RideRequest::clear_dest_long() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dest_long_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline double RideRequest::dest_long() const {
  // @@protoc_insertion_point(field_get:vahan_mesh.RideRequest.dest_long)
  return _internal_dest_long();
}
inline void RideRequest::set_dest_long(double value) {
  _internal_set_dest_long(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:vahan_mesh.RideRequest.dest_long)
}
inline double RideRequest::_internal_dest_long() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dest_long_;
}
inline void RideRequest::_internal_set_dest_long(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dest_long_ = value;
}

// int32 rider_rating = 6;
inline void RideRequest::clear_rider_rating() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rider_rating_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::int32_t RideRequest::rider_rating() const {
  // @@protoc_insertion_point(field_get:vahan_mesh.RideRequest.rider_rating)
  return _internal_rider_rating();
}
inline void RideRequest::set_rider_rating(::int32_t value) {
  _internal_set_rider_rating(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:vahan_mesh.RideRequest.rider_rating)
}
inline ::int32_t RideRequest::_internal_rider_rating() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rider_rating_;
}
inline void RideRequest::_internal_set_rider_rating(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rider_rating_ = value;
}

// .vahan_mesh.RideRequest.ServiceType requested_type = 7;
inline void RideRequest::clear_requested_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.requested_type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::vahan_mesh::RideRequest_ServiceType RideRequest::requested_type() const {
  // @@protoc_insertion_point(field_get:vahan_mesh.RideRequest.requested_type)
  return _internal_requested_type();
}
inline void RideRequest::set_requested_type(::vahan_mesh::RideRequest_ServiceType value) {
  _internal_set_requested_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:vahan_mesh.RideRequest.requested_type)
}
inline ::vahan_mesh::RideRequest_ServiceType RideRequest::_internal_requested_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::vahan_mesh::RideRequest_ServiceType>(_impl_.requested_type_);
}
inline void RideRequest::_internal_set_requested_type(::vahan_mesh::RideRequest_ServiceType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.requested_type_ = value;
}

// -------------------------------------------------------------------

// Cab

// string cab_id = 1;
inline void Cab::clear_cab_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cab_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Cab::cab_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:vahan_mesh.Cab.cab_id)
  return _internal_cab_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Cab::set_cab_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.cab_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:vahan_mesh.Cab.cab_id)
}
inline ::std::string* PROTOBUF_NONNULL Cab::mutable_cab_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_cab_id();
  // @@protoc_insertion_point(field_mutable:vahan_mesh.Cab.cab_id)
  return _s;
}
inline const ::std::string& Cab::_internal_cab_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cab_id_.Get();
}
inline void Cab::_internal_set_cab_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cab_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Cab::_internal_mutable_cab_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.cab_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Cab::release_cab_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:vahan_mesh.Cab.cab_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.cab_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.cab_id_.Set("", GetArena());
  }
  return released;
}
inline void Cab::set_allocated_cab_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.cab_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.cab_id_.IsDefault()) {
    _impl_.cab_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:vahan_mesh.Cab.cab_id)
}

// double lat = 2;
inline void Cab::clear_lat() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lat_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline double Cab::lat() const {
  // @@protoc_insertion_point(field_get:vahan_mesh.Cab.lat)
  return _internal_lat();
}
inline void Cab::set_lat(double value) {
  _internal_set_lat(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:vahan_mesh.Cab.lat)
}
inline double Cab::_internal_lat() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lat_;
}
inline void Cab::_internal_set_lat(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lat_ = value;
}

// double lon = 3;
inline void Cab::clear_lon() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lon_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline double Cab::lon() const {
  // @@protoc_insertion_point(field_get:vahan_mesh.Cab.lon)
  return _internal_lon();
}
inline void Cab::set_lon(double value) {
  _internal_set_lon(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:vahan_mesh.Cab.lon)
}
inline double Cab::_internal_lon() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lon_;
}
inline void Cab::_internal_set_lon(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lon_ = value;
}

// bool is_available = 4;
inline void Cab::clear_is_available() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_available_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline bool Cab::is_available() const {
  // @@protoc_insertion_point(field_get:vahan_mesh.Cab.is_available)
  return _internal_is_available();
}
inline void Cab::set_is_available(bool value) {
  _internal_set_is_available(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:vahan_mesh.Cab.is_available)
}
inline bool Cab::_internal_is_available() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_available_;
}
inline void Cab::_internal_set_is_available(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_available_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace vahan_mesh


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::vahan_mesh::RideRequest_ServiceType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::vahan_mesh::RideRequest_ServiceType>() {
  return ::vahan_mesh::RideRequest_ServiceType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // rider_2eproto_2epb_2eh
